### ISSUE TITLE
Some thoughts

### ISSUE THREAD

**Issue by ladasfeed** [GithubActionTastingOrg/AutoMergeAction#31]
Hello!

Marked condition will return true or 'REVIEW_REQUIRED'

![image](https://user-images.githubusercontent.com/57018343/203795762-efdd0439-611e-4393-83f6-81c803bc02cf.png)

Mb you meant:
```['CHANGES_REQUESTED', 'REVIEW_REQUIRED'].includes(pullRequest.reviewDecision)```

---

Maybe we can use fields `head` or `base` for filtering pull requests, instead of pullRequest.baseRefName !== headBranch
https://octokit.github.io/rest.js/v19#pulls-list

![image](https://user-images.githubusercontent.com/57018343/203805361-ad9b08ff-43ff-4359-8dde-05d31126c0d3.png)

---
Do we really need that? Is information from `octokit.rest.pulls.list` not enough? 

![image](https://user-images.githubusercontent.com/57018343/203804346-c061398e-370e-480d-939c-fcae52d57722.png)

**Comment by corbie1** [comment]
1. You are right, thanks
2. Yes, it can be done
3. Unfortunately, this request does not have all the necessary fields
